# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_POWER_AVS)		+= avs/
obj-$(CONFIG_POWER_RESET)	+= reset/
obj-$(CONFIG_POWER_SUPPLY)	+= supply/
obj-$(CONFIG_TCPC_RT1711H)	+= rt-charger.o
obj-$(CONFIG_ARCH_QCOM)          += qcom/
