obj-y += stmvl53l5.o
stmvl53l5-objs += stmvl53l5_module.o stmvl53l5_i2c.o stmvl53l5_spi.o stmvl53l5_load_fw.o asus_module.o

#all :
#	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules
#clean :
#	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean
